import type { RegistrZdroj } from "./typy";

/**
 * Registr veřejných zdrojů.
 *
 * Přidání zdroje = jeden záznam v tomhle poli. Nic jiného se nemění.
 * Nový záznam vždy s `overenaAdresa: false`; `npm run sber:zdroje` vypíše,
 * které adresy skutečně odpovídají, a teprve pak se příznak přepne.
 */

/**
 * Fráze o vyhlášení. Sloveso s předmětem, ne téma.
 *
 * Kdyby tu stálo jen „mobilizace“, trefila by se každá stránka, která to slovo
 * někde v archivu nebo v menu má — a zápor by se nepotvrdil nikdy.
 */
const PRAVNI_VYHLASENI = [
  "vyhlasil stav ohrozeni statu",
  "vyhlasila stav ohrozeni statu",
  "vyhlaseni stavu ohrozeni statu",
  "vyhlasil valecny stav",
  "vyhlaseni valecneho stavu",
  "narizuje mobilizaci",
  "naridil mobilizaci",
  "vyhlaseni mobilizace",
  "vyhlasila nouzovy stav",
  "vyhlasil nouzovy stav",
  "vyhlaseni nouzoveho stavu",
  "zakaz vycestovani",
  "zakazuje vycestovani",
  "znovuzavedeni ochrany vnitrnich hranic",
  "obnovuje hranicni kontroly",
  "uzavira hranicni prechody",
];

/** Tematická slova — jen ke kontrole, zápor neblokují. */
const PRAVNI_TEMATA = [
  "stav ohrozeni statu",
  "mobilizace",
  "nouzovy stav",
  "hranicni kontroly",
  "omezeni vycestovani",
];

const PROVOZNI_VYHLASENI = [
  "vyhlasil stav nouze",
  "vyhlasila stav nouze",
  "vyhlaseni stavu nouze",
  "vyhlasen stav nouze",
  "omezeni odberu",
  "regulacni stupen",
  "vyhlasil stav kyberneticke",
  "vyhlaseni stavu kyberneticke",
  "stav kybernetickeho nebezpeci",
];

const PROVOZNI_TEMATA = ["stav nouze", "rozsahly vypadek", "krizove opatreni"];

export const ZDROJE: RegistrZdroj[] = [
  /* ---------- právní stav ČR ---------- */
  {
    klic: "e-sbirka",
    nazev: "e-Sbírka — úřední sbírka právních předpisů",
    druh: "pravni",
    url: "https://www.e-sbirka.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: PRAVNI_VYHLASENI,
    sledovana: PRAVNI_TEMATA,
    tyka: ["stav-ohrozeni", "valecny-stav", "mobilizace", "nouzovy-stav"],
    overenaAdresa: false,
  },
  {
    klic: "vlada",
    nazev: "Vláda ČR — tiskové zprávy",
    druh: "pravni",
    url: "https://vlada.gov.cz/cz/media-centrum/tiskove-zpravy/",
    odkaz: "https://vlada.gov.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: PRAVNI_VYHLASENI,
    sledovana: PRAVNI_TEMATA,
    tyka: ["stav-ohrozeni", "nouzovy-stav", "hranice", "bezny-zivot"],
    overenaAdresa: false,
  },
  {
    klic: "psp",
    nazev: "Poslanecká sněmovna Parlamentu ČR",
    druh: "pravni",
    url: "https://www.psp.cz/sqw/hp.sqw",
    odkaz: "https://www.psp.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: [...PRAVNI_VYHLASENI, "mimoradna schuze k bezpecnostni"],
    sledovana: [...PRAVNI_TEMATA, "mimoradna schuze"],
    tyka: ["stav-ohrozeni", "valecny-stav", "schuze-parlamentu"],
    overenaAdresa: false,
  },
  {
    klic: "hrad",
    nazev: "Prezident republiky — tiskové zprávy",
    druh: "pravni",
    url: "https://www.hrad.cz/cs/pro-media/tiskove-zpravy",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: ["narizuje mobilizaci", "naridil mobilizaci", "vyhlasil valecny stav"],
    sledovana: ["mobilizace"],
    tyka: ["mobilizace"],
    overenaAdresa: false,
  },
  {
    klic: "mvcr",
    nazev: "Ministerstvo vnitra ČR",
    druh: "pravni",
    url: "https://www.mvcr.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: PRAVNI_VYHLASENI,
    sledovana: [...PRAVNI_TEMATA, "hranicni kontroly"],
    tyka: ["hranice", "vycestovani"],
    overenaAdresa: false,
  },
  {
    klic: "mzv",
    nazev: "Ministerstvo zahraničních věcí — cestování",
    druh: "instituce",
    url: "https://mzv.gov.cz/jnp/cz/cestujeme/index.html",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: ["opustte zemi", "okamzite opustte", "evakuace obcanu cr"],
    sledovana: ["nedoporucuje cestovat", "evakuace"],
    tyka: ["vycestovani", "evakuace"],
    overenaAdresa: false,
  },

  /* ---------- NATO a spojenci ---------- */
  {
    klic: "nato",
    nazev: "NATO — Newsroom",
    druh: "instituce",
    url: "https://www.nato.int/cps/en/natohq/news.htm",
    format: "html",
    jazyk: "en",
    primarni: true,
    klicova: [
      "invoked article 4", "invoke article 4", "invoked article 5", "invoke article 5",
      "invoking article 4", "invoking article 5",
      "requested consultations under article 4", "consultations under article 4 of",
      "has been invoked",
    ],
    sledovana: ["article 4 consultations", "north atlantic council will meet"],
    tyka: ["clanek-4", "clanek-5", "readiness"],
    overenaAdresa: false,
  },
  {
    klic: "army",
    nazev: "Ministerstvo obrany ČR",
    druh: "instituce",
    url: "https://mo.gov.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: ["narizuje mobilizaci", "naridil mobilizaci", "vyhlasena bojova pohotovost"],
    sledovana: ["mobilizace", "zvysena pohotovost"],
    tyka: ["mobilizace", "readiness"],
    overenaAdresa: false,
  },

  /* ---------- provoz: energetika ---------- */
  {
    klic: "ceps",
    nazev: "ČEPS — přenosová soustava",
    druh: "provoz",
    url: "https://www.ceps.cz/cs/aktuality",
    odkaz: "https://www.ceps.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: PROVOZNI_VYHLASENI,
    sledovana: PROVOZNI_TEMATA,
    tyka: ["elektrina"],
    overenaAdresa: false,
  },
  {
    klic: "eru",
    nazev: "Energetický regulační úřad",
    druh: "provoz",
    url: "https://www.eru.gov.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: PROVOZNI_VYHLASENI,
    sledovana: PROVOZNI_TEMATA,
    tyka: ["elektrina", "plyn"],
    overenaAdresa: false,
  },
  {
    klic: "ote",
    nazev: "OTE — operátor trhu",
    druh: "provoz",
    url: "https://www.ote-cr.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: PROVOZNI_VYHLASENI,
    sledovana: PROVOZNI_TEMATA,
    tyka: ["plyn", "elektrina"],
    overenaAdresa: false,
  },

  /* ---------- provoz: palivo, peníze, sítě ---------- */
  {
    klic: "sshr",
    nazev: "Správa státních hmotných rezerv",
    druh: "provoz",
    url: "https://www.sshr.gov.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: ["uvolneni nouzovych zasob", "regulace prodeje pohonnych", "vyhlasil stav nouze"],
    sledovana: ["nouzove zasoby"],
    tyka: ["palivo"],
    overenaAdresa: false,
  },
  {
    klic: "mpo",
    nazev: "Ministerstvo průmyslu a obchodu",
    druh: "provoz",
    url: "https://mpo.gov.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: PROVOZNI_VYHLASENI,
    sledovana: [...PROVOZNI_TEMATA, "pohonne hmoty"],
    tyka: ["palivo", "elektrina", "plyn"],
    overenaAdresa: false,
  },
  {
    klic: "cnb",
    nazev: "Česká národní banka — tiskové zprávy",
    druh: "provoz",
    url: "https://www.cnb.cz/cs/cnb-news/tiskove-zpravy/",
    odkaz: "https://www.cnb.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: ["omezeni platebniho styku", "vypadek platebniho systemu", "omezeni vyberu hotovosti"],
    sledovana: ["platebni styk"],
    tyka: ["banky"],
    overenaAdresa: false,
  },
  {
    klic: "ctu",
    nazev: "Český telekomunikační úřad",
    druh: "provoz",
    url: "https://ctu.gov.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: ["rozsahly vypadek site", "celostatni vypadek", "vyhlasil stav nouze"],
    sledovana: ["vypadek site"],
    tyka: ["komunikace"],
    overenaAdresa: false,
  },
  {
    klic: "nukib",
    nazev: "NÚKIB — Národní úřad pro kybernetickou a informační bezpečnost",
    druh: "provoz",
    url: "https://nukib.gov.cz/cs/infoservis/aktuality/",
    odkaz: "https://nukib.gov.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: ["vyhlasil stav kyberneticke", "stav kybernetickeho nebezpeci", "vyhlaseni stavu kyberneticke"],
    sledovana: ["zavazny kyberneticky incident"],
    tyka: ["komunikace", "kyber"],
    overenaAdresa: false,
  },
  {
    klic: "hzs",
    nazev: "Hasičský záchranný sbor ČR",
    druh: "provoz",
    url: "https://www.hzscr.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: ["vyhlasen stav nebezpeci", "vyhlasil stav nebezpeci", "vyhlasen nouzovy stav"],
    sledovana: ["krizove opatreni"],
    tyka: ["bezny-zivot"],
    overenaAdresa: false,
  },
  {
    klic: "dopravni-info",
    nazev: "Dopravní info (ŘSD)",
    druh: "provoz",
    url: "https://www.dopravniinfo.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: ["uzavreni hranicniho prechodu", "uzavreny hranicni prechod"],
    sledovana: ["hranicni kontroly", "omezeni nakladni dopravy"],
    tyka: ["hranice"],
    overenaAdresa: false,
  },
  {
    klic: "policie",
    nazev: "Policie ČR",
    druh: "instituce",
    url: "https://www.policie.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: ["obnoveni hranicnich kontrol", "zavedeni hranicnich kontrol"],
    sledovana: ["sabotaz", "kriticka infrastruktura"],
    tyka: ["hranice"],
    overenaAdresa: false,
  },
];

export function zdroj(klic: string): RegistrZdroj | undefined {
  return ZDROJE.find((z) => z.klic === klic);
}
