import type { RegistrZdroj } from "./typy";

/**
 * Registr veřejných zdrojů.
 *
 * Přidání zdroje = jeden záznam v tomhle poli. Nic jiného se nemění.
 * Nový záznam vždy s `overenaAdresa: false`; `npm run sber:zdroje` vypíše,
 * které adresy skutečně odpovídají, a teprve pak se příznak přepne.
 */

const PRAVNI_SIGNALY = [
  "stav ohrozeni statu",
  "valecny stav",
  "mobilizace",
  "nouzovy stav",
  "krizovy stav",
  "zakaz vycestovani",
  "omezeni vycestovani",
  "znovuzavedeni kontrol",
  "ochrana vnitrnich hranic",
  "uzavreni hranic",
];

const PROVOZNI_SIGNALY = [
  "stav nouze",
  "omezeni odberu",
  "regulacni stupen",
  "rozsahly vypadek",
  "krizove opatreni",
  "kyberneticke nebezpeci",
  "vyhlasil stav",
];

export const ZDROJE: RegistrZdroj[] = [
  /* ---------- právní stav ČR ---------- */
  {
    klic: "e-sbirka",
    nazev: "e-Sbírka — úřední sbírka právních předpisů",
    druh: "pravni",
    url: "https://www.e-sbirka.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: PRAVNI_SIGNALY,
    tyka: ["stav-ohrozeni", "valecny-stav", "mobilizace", "nouzovy-stav"],
    overenaAdresa: false,
  },
  {
    klic: "vlada",
    nazev: "Vláda ČR — tiskové zprávy",
    druh: "pravni",
    url: "https://vlada.gov.cz/cz/media-centrum/tiskove-zpravy/",
    odkaz: "https://vlada.gov.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: PRAVNI_SIGNALY,
    tyka: ["stav-ohrozeni", "nouzovy-stav", "hranice", "bezny-zivot"],
    overenaAdresa: false,
  },
  {
    klic: "psp",
    nazev: "Poslanecká sněmovna Parlamentu ČR",
    druh: "pravni",
    url: "https://www.psp.cz/sqw/hp.sqw",
    odkaz: "https://www.psp.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: [...PRAVNI_SIGNALY, "mimoradna schuze"],
    tyka: ["stav-ohrozeni", "valecny-stav", "schuze-parlamentu"],
    overenaAdresa: false,
  },
  {
    klic: "hrad",
    nazev: "Prezident republiky — tiskové zprávy",
    druh: "pravni",
    url: "https://www.hrad.cz/cs/pro-media/tiskove-zpravy",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: ["mobilizace", "valecny stav"],
    tyka: ["mobilizace"],
    overenaAdresa: false,
  },
  {
    klic: "mvcr",
    nazev: "Ministerstvo vnitra ČR",
    druh: "pravni",
    url: "https://www.mvcr.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: [...PRAVNI_SIGNALY, "hranicni kontroly"],
    tyka: ["hranice", "vycestovani"],
    overenaAdresa: false,
  },
  {
    klic: "mzv",
    nazev: "Ministerstvo zahraničních věcí — cestování",
    druh: "instituce",
    url: "https://mzv.gov.cz/jnp/cz/cestujeme/index.html",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: ["nedoporucuje cestovat", "evakuace", "opustte zemi"],
    tyka: ["vycestovani"],
    overenaAdresa: false,
  },

  /* ---------- NATO a spojenci ---------- */
  {
    klic: "nato",
    nazev: "NATO — Newsroom",
    druh: "instituce",
    url: "https://www.nato.int/cps/en/natohq/news.htm",
    format: "html",
    jazyk: "en",
    primarni: true,
    klicova: ["article 4", "article 5", "invoked", "consultations under article"],
    tyka: ["clanek-4", "clanek-5", "readiness"],
    overenaAdresa: false,
  },
  {
    klic: "army",
    nazev: "Armáda ČR",
    druh: "instituce",
    url: "https://army.gov.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: ["mobilizace", "zvysena pohotovost", "bojova pohotovost"],
    tyka: ["mobilizace", "readiness"],
    overenaAdresa: false,
  },

  /* ---------- provoz: energetika ---------- */
  {
    klic: "ceps",
    nazev: "ČEPS — přenosová soustava",
    druh: "provoz",
    url: "https://www.ceps.cz/cs/aktuality",
    odkaz: "https://www.ceps.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: PROVOZNI_SIGNALY,
    tyka: ["elektrina"],
    overenaAdresa: false,
  },
  {
    klic: "eru",
    nazev: "Energetický regulační úřad",
    druh: "provoz",
    url: "https://www.eru.gov.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: PROVOZNI_SIGNALY,
    tyka: ["elektrina", "plyn"],
    overenaAdresa: false,
  },
  {
    klic: "ote",
    nazev: "OTE — operátor trhu",
    druh: "provoz",
    url: "https://www.ote-cr.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: PROVOZNI_SIGNALY,
    tyka: ["plyn", "elektrina"],
    overenaAdresa: false,
  },

  /* ---------- provoz: palivo, peníze, sítě ---------- */
  {
    klic: "sshr",
    nazev: "Správa státních hmotných rezerv",
    druh: "provoz",
    url: "https://www.sshr.gov.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: ["uvolneni zasob", "nouzove zasoby", "regulace prodeje", "stav nouze"],
    tyka: ["palivo"],
    overenaAdresa: false,
  },
  {
    klic: "mpo",
    nazev: "Ministerstvo průmyslu a obchodu",
    druh: "provoz",
    url: "https://mpo.gov.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: [...PROVOZNI_SIGNALY, "pohonne hmoty"],
    tyka: ["palivo", "elektrina", "plyn"],
    overenaAdresa: false,
  },
  {
    klic: "cnb",
    nazev: "Česká národní banka — tiskové zprávy",
    druh: "provoz",
    url: "https://www.cnb.cz/cs/cnb-news/tiskove-zpravy/",
    odkaz: "https://www.cnb.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: ["omezeni platebniho styku", "vypadek platebniho", "stav nouze", "opatreni k platebnimu styku"],
    tyka: ["banky"],
    overenaAdresa: false,
  },
  {
    klic: "ctu",
    nazev: "Český telekomunikační úřad",
    druh: "provoz",
    url: "https://ctu.gov.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: ["rozsahly vypadek", "vypadek site", "stav nouze"],
    tyka: ["komunikace"],
    overenaAdresa: false,
  },
  {
    klic: "nukib",
    nazev: "NÚKIB — Národní úřad pro kybernetickou a informační bezpečnost",
    druh: "provoz",
    url: "https://nukib.gov.cz/cs/infoservis/aktuality/",
    odkaz: "https://nukib.gov.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: ["kyberneticke nebezpeci", "stav kyberneticke", "vyhlasil", "zavazny kyberneticky incident"],
    tyka: ["komunikace", "kyber"],
    overenaAdresa: false,
  },
  {
    klic: "hzs",
    nazev: "Hasičský záchranný sbor ČR",
    druh: "provoz",
    url: "https://www.hzscr.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: ["krizove opatreni", "stav nebezpeci", "nouzovy stav"],
    tyka: ["bezny-zivot"],
    overenaAdresa: false,
  },
  {
    klic: "dopravni-info",
    nazev: "Dopravní info (ŘSD)",
    druh: "provoz",
    url: "https://www.dopravniinfo.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: ["uzavreni hranicniho prechodu", "hranicni kontroly", "omezeni nakladni dopravy"],
    tyka: ["hranice"],
    overenaAdresa: false,
  },
  {
    klic: "policie",
    nazev: "Policie ČR",
    druh: "instituce",
    url: "https://www.policie.cz/",
    format: "html",
    jazyk: "cs",
    primarni: true,
    klicova: ["sabotaz", "hranicni kontroly", "kriticka infrastruktura"],
    tyka: ["hranice"],
    overenaAdresa: false,
  },
];

export function zdroj(klic: string): RegistrZdroj | undefined {
  return ZDROJE.find((z) => z.klic === klic);
}
