import { chromium } from "playwright";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const p = await b.newPage({ viewport: { width: 1440, height: 940 } });
const chyby = []; p.on("pageerror", (e) => chyby.push(String(e)));
await p.goto("http://localhost:4400/#/trend/", { waitUntil: "networkidle" });
await p.waitForTimeout(600);
const r = p.locator('input[type="range"]').first();
console.log("dnů na ose:", Number(await r.getAttribute("max")) + 1);
const konec = await p.locator("text=Stav k datu").first().isVisible();
await r.fill("30"); await p.waitForTimeout(300);
await p.screenshot({ path: "/tmp/snap/p-30.png" });
const den30 = await p.locator("p.cislice").first().innerText();
await r.fill("31"); await p.waitForTimeout(300);
const den31 = await p.locator("p.cislice").first().innerText();
console.log("hlavička:", konec, "| den 30:", den30, "-> den 31:", den31);
const zmeny = await p.locator("text=Poslední změna").count();
console.log("dny bez změny mají popisek 'Poslední změna':", zmeny > 0);
await p.screenshot({ path: "/tmp/snap/p-posuvnik.png" });
console.log("chyby:", chyby.length ? chyby.slice(0,3) : "žádné");
await b.close();
